books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index),
    path('api/', views.books),
    path('api/<str:name>', views.search),
]

status/urls.py
from django.urls import path
from . import views

app_name = "status"

urlpatterns = [
    path('', views.index, name="index"),
    path('add_status', views.add_status, name='add_status'),
]

subscriber/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('validate/', views.validate, name="validate"),
    path('subscriber/', views.subscriber, name="subscriber"),
    path('result/', views.result, name="result"),
    path('unsubscribe/', views.unsubscribe, name='unsubscribe'),

]

wdplab/urls.py
from django.contrib import admin
from django.urls import path, include
from status import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('status/', include('status.urls')),
    path('', views.profile, name='profile'),
    path('books/', include('books.urls')),
    path('subscribe/', include('subscriber.urls')),
]

books/models.py
from django.db import models

# Create your models here.

status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    text = models.CharField(max_length=300)
    time = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Statuses'

subscriber/models.py
from django.db import models

# Create your models here.
class Subscriber(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField(max_length=20)
    password = models.CharField(max_length=20)

status/forms.py
from django import forms

class StatusForm(forms.Form):
    text = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': "Enter your status here",
        'required': True,
    }), max_length=300)

subscriber/forms.py
from django import forms

class SubscriberForm(forms.Form):
    name = forms.CharField(widget = forms.TextInput(attrs = {
        'id': 'name',
        'placeholder': 'Name',
        'required': True,
    })) 
    email = forms.EmailField(widget = forms.EmailInput(attrs = {
        'id': 'email',
        'placeholder': 'Email',
        'required': True,
    }))
    password = forms.CharField(widget = forms.PasswordInput(attrs= {
        'id': 'password',
        'placeholder': 'Password',
        'required': True,
    }))

books/views.py
from django.shortcuts import render
from django.http import HttpResponse
import requests
import json

# Create your views here.
def index(request):
    data = {}
    return render(request, "books.html", data)

def books(request):
    response = requests.get("https://www.googleapis.com/books/v1/volumes?q=quilting")
    books_data = response.json()
    books_data = {"books": books_data["items"]}
    books_json_data = json.dumps(books_data)
    return HttpResponse(books_json_data, content_type="application/json")

def search(request, name):
    response = requests.get("https://www.googleapis.com/books/v1/volumes?q=" + name)
    books_data = response.json()
    books_data = {"books": books_data["items"]}
    books_json_data = json.dumps(books_data)
    return HttpResponse(books_json_data, content_type="application/json")

    

status/views.py
from django.shortcuts import render, redirect
from . import forms
from .models import Status

# Create your views here.
def index(request):
    statuses = Status.objects.all()
    status_form = forms.StatusForm()
    response = {"statuses" : statuses, "status_form" : status_form}
    return render(request, 'index.html', response)

def add_status(request):
    status_form = forms.StatusForm(request.POST)
    if request.method == "POST" and status_form.is_valid():
        Status.objects.create(text = status_form.cleaned_data['text'])
    return redirect('status:index')

def profile(request):
    return render(request, 'profile.html')

subscriber/views.py
from django.http import JsonResponse
from django.shortcuts import render
from .forms import SubscriberForm
from .models import Subscriber

# Create your views here.
def index(request):
    form = SubscriberForm(request.POST)
    if request.method == "POST" and form.is_valid():
        data = form.cleaned_data
        status_subscribe = True
        try:
            Subscriber.objects.create(**data)
        except:
            status_subscribe = False
        return JsonResponse({'status_subscribe': status_subscribe})
    return render(request, 'subscriber.html', {'form': form})

def validate(request):
    if request.method == "POST":
        exists = Subscriber.objects.filter(email = request.POST['email']).first()
        return JsonResponse({'exists': exists})
        

def subscriber(request):
    if request.method == "POST":
        subscriber = Subscriber.objects.all().values()
        subscriberList = list(subscriber)
        return JsonResponse({'subscriberList': subscriberList})

def result(request):
    return render(request, 'subscriber-data.html')

def unsubscribe(request):
    if request.method == "POST":
        Subscriber.objects.filter(email = request.POST['email']).delete()
        now = list(Subscriber.objects.all().values())
        return JsonResponse({'unsubscribed': True, 'now': now})

books/templates/books.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="shortcut icon" href="{% static 'img/icon.png' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link id="page-style" rel="stylesheet" type="text/css" href="{% static 'books/css/styles.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
        <title>Books</title>
    </head>
   <body class="body-con">
	<div class="search-con">
		<input class="search-input" type="text" placeholder="Search">
		<button id="search-button">Search</button>
	</div>
	<div class="star-counter-con">
		<img class="star-icon" src="{% static 'books/css/svg/star.svg' %}">
		<div class="counter-number">0</div>
	</div>
	<table class="book-con">
		<thead>
			<tr>
				<th>Title</th>
				<th>Authors</th>
				<th>Publisher</th>
				<th>Published Date</th>
				<th></th>
			</tr>
		</thead>
		<tbody id="books"></tbody>
	</table>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="{% static 'books/js/script.js' %}" charset="utf-8"></script>
</html>

status/templates/index.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="shortcut icon" href="{% static 'img/icon.png' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link id="page-style" rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
        <title>Status</title>
    </head>

    <body data-spy="scroll" data-target=".navbar" data-offset="0">
        <div class="w-100 full-height d-flex align-items-center">
            <section class="container main">
                <div class="text-center">
                    <a href="{% url 'profile' %}" class="btn btn-dark none-bg">My profile</a>
                    <br>
                    <br>
                    <h1 class="bold white-text">Hello apa kabar?</h1>
                    <form class="site-form w-100" action="{% url 'status:add_status' %}" method="POST">
                        <div>
                            {% csrf_token %}
                            {% for field in status_form.visible_fields %}
                                {{ field }}
                            {% endfor %}
                        </div>
                        <button class="btn btn-dark height-control" type="submit">Create</button>
                    </form>
                    <div class="status-entries">
                        {% for s in statuses %}
                            <div class="cont-list">
                                <h4 class="bold white-text status-margin"><span>Timestamp: {{ s.time }}</span></h4>
                                <h4 class="bold white-text status-margin"><span>{{ s.text }}</span></h4>
                            </div>
                        {% empty %}
                            <h4 class="bold white-text">No status available!</h4>
                        {% endfor %}
                    </div>
                </div>
            </section>
        </div>
    </body>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</html>

status/templates/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="shortcut icon" href="{% static 'img/icon.png' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link id="page-style" rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
        <title>Profile</title>
    </head>
    <body>
        <div id="preloader">
            <div id="status">&nbsp;</div>
        </div>
        <div class="profile-content white-text">
            <div>
                <img src="{% static 'status/img/hotman.jpg' %}" alt="Photo" class="img-thumbnail photo-margin">
                <h1>Hi! My name is Samuel.</h1>
                <h2>Full stack web developer, politics enthusiast</h2>
                <br>
                <a href="{% url 'status:index' %}" class="btn btn-dark">My status</a>
                <a href="#" class="btn btn-dark" id="toggle-style-sheet" onclick="toggle_style()" value="LIGHT">Change theme</a>
            </div>
        </div>
        <div class="container">
            <button class="accordion item-one">Activities</button>
            <div class="panel">
                <ul>
                    <li>Full stack web developer</li>
                    <li>Politics observer</li>
                    <li>Classical musician</li>
                </ul>
            </div>
            <button class="accordion item-two">Commitee experiences</button>
            <div class="panel">
                <ul>
                    <li>BEM Fasilkom UI 2018</li>
                    <li>The 25th Computers Get Together</li>
                    <li>PMB Fasilkom UI 2018</li>
                    <li>Pemira Fasilkom UI 2018</li>
                    <li>Indonesia Model United Nations 2018</li>
                </ul>
            </div>
            <button class="accordion item-three">Achievements</button>
            <div class="panel">
                <ul>
                    <li>1st winner for National Web and Application Development Comptetition</li>
                    <li>Best Speaker for Harvard World Model United Nations 2017</li>
                    <li>Best Technique for International Opera Competition</li>
                </ul>
            </div>
        </div>
    </body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'status/js/dropdown.js' %}"></script>
    <script>
        var normal_src = "{% static 'css/styles.css' %}";
        var revert_src = "{% static 'status/css/revert.css' %}"; 
    </script>
    <script type="text/javascript" src="{% static 'status/js/changeTheme.js' %}"></script>
    <script type="text/javascript" src="{% static 'status/js/preloader.js' %}"></script>
</html>

subscriber/templates/subscriber-data.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link id="page-style" rel="stylesheet" type="text/css" href="{% static 'css/subscriber.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <title>Subscribe Now!</title>
</head>
<body onload="renderResult()">
    {% csrf_token %}
    <div id="res" class="result">
    </div>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="{% static 'js/subscriber.js' %}" charset="utf-8"></script>
<script>
    function renderResult() {
    var csrftoken = $("[name=csrfmiddlewaretoken]").val();

    $.ajax({
        method: 'POST',
        url: 'http://samueldimas.herokuappc.com/subscribe/subscriber/',
        headers: {
            "X-CSRFToken": csrftoken
        },
        success: function (result) {
            var length_arr = result.subscriberList.length;
            var data = result.subscriberList;
            for (var i = 0; i < length_arr; i++) {
                var name = data[i]['nama'];
                var email = data[i]['email'];
                var button = '<button class="btn" id=' + email + ' onclick=unsubscribe(this)>' + 'UNSUBSCRIBE' + '</button>';
                var show = '<div class = "hasil">' + name + " " + email + button + '</div>' ;
                var container = '<div>' + show + '</div>';
                $('.result').append(container)
            }
        }
    })
}

    function unsubscribe(t) {
        var csrftoken = $("[name=csrfmiddlewaretoken]").val();
        var email = t.id;
        $.ajax({
            method: 'POST',
            url: "{% url 'unsubscribe' %}",
            headers: {
                "X-CSRFToken": csrftoken
            },
            data: {email: email},
            success: function (res) {
                console.log('success');
                $('#res').replaceWith("<div id='res' class='result'></div>");
                var length_arr = res.now.length;
                var data = res.now;
                for (var i = 0; i < length_arr; i++) {
                    var name = data[i]['nama'];
                    var email = data[i]['email'];
                    var button = '<button class="btn" id=' + email + ' onclick=unsubscribe(this)>' + 'UNSUBSCRIBE' + '</button>';
                    var show = '<div class = "hasil">' + name + " " + email + button + '</div>' ;
                    $('.result').append(show)
                }
            }
        })
    }

</script>
</html>

subscriber/templates/subscriber.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link id="page-style" rel="stylesheet" type="text/css" href="{% static 'css/subscriber.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <title>Subscribe Now!</title>
</head>
<body>
    <div class="padding-content">
        <div class="center-item">
            <div class="form-item">
                <form action="POST">
                    {% csrf_token %}
                    <div class="enter">
                        <div id="form_subscribe" class="form_data">
                            <label for="{{ form.name.id_for_label }}">Name: </label>
                            
                            {{ form.name }}
                            <div id = "form_name" class = "alert"> *Name is required </div>
                        </div>
                        <div class="form_data">
                            <label for="{{ form.email.id_for_label }}">Email: </label>
                            {{ form.email }}
                            <div id = "form_email" class = "alert"> *Valid email is required </div>
                            <div id = "form_email2" class = "alert"> *Email already registered </div>
                        </div>
                        <div class="form_data">
                                <label for="{{ form.password.id_for_label }}">Password: </label>
                            {{ form.password }}
                        <div id = "form_password" class = "alert"> *Password is required </div>
                    </div>
                    <div class="button_subscribe">
                        <input class="submit btn btn-success" type="submit" id="submit_subscribe" value="SUBSCRIBE">
                    </div>
                    <br>
                    <div class="result_data">  <a class="result_subscribe btn btn-primary" href="{% url 'result' %}"> Subscriber </a> </div>
                </form>
            </div>
        </div>
    </div>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="{% static 'js/subscriber.js' %}" charset="utf-8"></script>
</html>